export const routeList = [{
  title:"首页",
  name:"Index",
  path:"/index",
  key:'1',
  icon:"icon-shouye-zhihui"
},{
  title:"销项系统",
  name:"sims",
  path:"/sims",
  icon:"icon-caidan",
  key:'2',
  children:[{
    title:"单据新增",
    name:"DocumentAdd",
    path:"/sims/documentAdd",
    key:'3',
    icon:"icon-caidan",
    children:[{
      title:"单据录入",
      name:"DucumentEnter",
      path:"/sims/documentAdd/ducumentEnter",
      icon:"icon-caidan",
      key:'4',
    },{
      title:"单据导入",
      name:"DucumentExport",
      path:"/sims/documentAdd/ducumentExport",
      icon:"icon-caidan",
      key:'6',
    },{
      title:"明细导入",
      name:"DetailExport",
      path:"/sims/documentAdd/detailExport",
      icon:"icon-caidan",
      key:'7',
    }]
  },{
    title:"单据管理",
    name:"DocumentManagement",
    path:"/sims/documentManagement",
    key:'8',
    icon:"icon-caidan",
    children:[{
      title:"单据修改",
      name:"DjEdit",
      path:"/sims/documentManagement/djEdit",
      icon:"icon-caidan",
      key:'9',
    },{
      title:"单据合并",
      name:"DjMerge",
      path:"/sims/documentManagement/djMerge",
      icon:"icon-caidan",
      key:'10',
    },{
      title:"单据拆分",
      name:"DjSplit",
      path:"/sims/documentManagement/djSplit",
      icon:"icon-caidan",
      key:'11',
    }]
  }]
}]