export const routeList = [{
  title:"首页",
  name:"Index",
  path:"/index",
  key:'1',
  icon:"icon-shouye-zhihui"
},{
  title:"系统管理",
  name:"sims",
  path:"/sims",
  icon:"icon-caidan",
  key:'2',
  children:[{
    title:"单据新增",
    name:"DocumentAdd",
    path:"/sims/documentAdd",
    key:'3',
    icon:"icon-caidan",
    children:[{
      title:"单据录入",
      name:"DucumentEnter",
      path:"/sims/documentAdd/ducumentEnter",
      icon:"icon-caidan",
      key:'4',
    },{
      title:"单据导入",
      name:"DucumentExport",
      path:"/sims/documentAdd/ducumentExport",
      icon:"icon-caidan",
      key:'6',
    },{
      title:"明细导入",
      name:"DetailExport",
      path:"/sims/documentAdd/detailExport",
      icon:"icon-caidan",
      key:'7',
    }]
  }]
}]